---
- name: Login and create namespace (simple)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_url: "https://api.ocp-uat.linux-plus.local:6443"
    ocp_username: "kubeadmin"
    ocp_password: "w6U5e-8aZQZ-eJLvE-DdEKj"
    insecure_skip_tls_verify: true

  collections:
    - community.okd
    - kubernetes.core

  tasks:
    - name: Authenticate to OpenShift
      community.okd.openshift_auth:
        host: "{{ api_url }}"
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        validate_certs: "{{ not (insecure_skip_tls_verify | bool) }}"
      register: ocp_auth

    - name: Ensure namespace exists
      kubernetes.core.k8s:
        host: "{{ api_url }}"
        api_key: "{{ ocp_auth.openshift_auth.api_key }}"
        validate_certs: "{{ not (insecure_skip_tls_verify | bool) }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "adel-ns-autpomation-vms"

    - name: Logout (revoke token)
      community.okd.openshift_auth:
        state: absent
        host: "{{ api_url }}"
        api_key: "{{ ocp_auth.openshift_auth.api_key }}"
        validate_certs: "{{ not (insecure_skip_tls_verify | bool) }}"
