---
- name: Deploy helix secret
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - kubernetes.core
    - community.general
  vars:
    ldap_user: ""
    ldap_password: ""
    validate_certs: false
    cluster_id: ""
    kubeconfig_b64: ""

    target_namespace: "bmc-k8s-logs"
    secret_name: "helix-pull-secret"
    dockerconfigjson_b64: "eyJhdXRocyI6eyJoZWxpeHJlcG8uYXJhbWNvLmNvbS5zYTo4NDQzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IkBNQHoxbmdOZWVEMmJCZXR0ZVIiLCJlbWFpbCI6ImFkbWluIiwiYXV0aCI6IllXUnRhVzQ2UUUxQWVqRnVaMDVsWlVReVlrSmxkSFJsVWc9PSJ9fX0="
  tasks:
    - name: fail if kubeconfig is empty 
      fail:
        msg: "EMPTY"
      when: kubeconfig_b64 is not defined or kubeconfig_b64 | trim == ""

    - name: fail if dockerconfigjson_b64 is empty 
      fail:
        msg: "EMPTY"
      when: dockerconfigjson_b64 is not defined or dockerconfigjson_b64 | trim == ""

    - name: create kubeconfig file
      copy:
        content: "{{ kubeconfig_b64 | trim | b64decode }}"
        dest: "/tmp/kubeconfig"
        mode: "0600"

    #---------------- Helix Secret --------------#    
    - name: Namespace helix logs
      kubernetes.core.k8s:
        state: present
        kubeconfig: "/tmp/kubeconfig"
        validate_certs: "{{ validate_certs }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ target_namespace }}"
            labels:
              controlled-by: Ansible

    - name: Secret Creation
      kubernetes.core.k8s:
        state: present
        kubeconfig: "/tmp/kubeconfig"
        validate_certs: "{{ validate_certs }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ target_namespace }}"
            labels:
              controlled-by: Ansible
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ dockerconfigjson_b64 }}"

    - name: Check Secret existance
      kubernetes.core.k8s_info:
        kubeconfig: "/tmp/kubeconfig"
        validate_certs: "{{ validate_certs }}"
        api_version: v1
        kind: Secret
        name: "{{ secret_name }}"
        namespace: "{{ target_namespace }}"
      register: helix_secret_check

    - name: Show confirmation
      debug:
        msg:
          - "{{ target_namespace }}"
          - "{{ secret_name }}"
          - "{{ helix_secret_check.resource | length > 0 }}"

