---
- name: Label Nodes
  hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - kubernetes.core
    - community.general
  vars:
    ldap_user: ""
    ldap_password: ""
    validate_certs: false
    cluster_id: ""
    kubeconfig_b64: ""
  tasks:
    - name: fail if kubeconfig is empty 
      fail:
        msg: "EMPTY"
      when: kubeconfig_b64 is not defined or kubeconfig_b64 | trim == ""
    - name: create kubeconfig file
      copy:
        content: "{{ kubeconfig_b64 | trim | b64decode }}"
        dest: "/tmp/kubeconfig"
        mode: "0600"

    - name: Create MachineConfig for Chrony Configuration
      kubernetes.core.k8s:
        state: present
        kubeconfig: "/tmp/kubeconfig"
        verify_ssl: "false"
        definition:
          apiVersion: machineconfiguration.openshift.io/v1
          kind: MachineConfig
          metadata:
            name: 99-workers-chrony-configuration
            labels:
              machineconfiguration.openshift.io/role: worker
              controlled-by: Ansible
          spec:
            config:
              ignition:
                version: 3.5.0
              storage:
                files:
                  - contents:
                      compression: ''
                      source: 'data:,server%2010.1.44.150%20iburst%0Adriftfile%20%2Fvar%2Flib%2Fchrony%2Fdrift%0Amakestep%201.0%203%0Artcsync%0Alogdir%20%2Fvar%2Flog%2Fchrony%0A'
                    mode: 420
                    overwrite: true
                    path: /etc/chrony.conf
                register: mc_result
    - name: Notify about pending node reboots/config updates
      debug:
        msg: >
          MachineConfig '40-workers-chrony-configuration' has been applied.
          The Machine Config Operator will now update Worker nodes.
          You may need to reboot nodes or wait for the MCO to apply the new config.

