---
- name: Create Quay Organization
  hosts: localhost
  gather_facts: false
  collections:
    - infra.quay_configuration
  vars:
    namespace_name: ""
    env_name: ""

  tasks:
    - name: Process namespace name to generate org_name
      set_fact:
        org_name: "ar-{{ env_name }}{{ namespace_name[6:] }}"

    - name: Create Quay Organization
      quay_organization:
        name: "{{ org_name }}"
        email: "info@rxconnect.com"  # أو الإيميل الخاص بالمؤسسة عندك
        state: present
        quay_host: https://quay.apps.paashub.aramco.com.sa
        quay_token: "{{ quay_token }}"
        validate_certs: false
