---

- name: Authenticate to OpenShift using token and manage clusters
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core
    - infra.quay_configuration
  vars:
    namespace_name: ""
    env_name: ""
    cluster_name: ""
    quay_host: "https://quay.apps.paashub.aramco.com.sa"
    ldap_user: "{{ ansible_user }}"
    ldap_password: "{{ ansible_password }}"
    validate_certs: false
    
  tasks:
    - name: Set cluster_api based on cluster_name
      set_fact:
        cluster_api: |
          {% if cluster_name == 'ibmdev' %}
          https://api.{{ cluster_name }}.aramco.com:6443
          {% else %}
          https://api.{{ cluster_name }}.aramco.com.sa:6443
          {% endif %}
    - name: Login to paashub
      command: >
        oc login {{ cluster_api }} -u {{ ldap_user }} -p {{ ldap_password }} --insecure-skip-tls-verify
      register: cluster_token
      failed_when: false
      no_log: true
      changed_when: false
    - name: Get Token of automation user
      command: oc whoami -t
      register: cluster_token
      changed_when: false
      failed_when: false
      no_log: true
    - name: set token cleaner
      ansible.builtin.set_fact:
        openshift_cluster_token: "{{ cluster_token.stdout | trim }}"

## openshift token is saved in openshift_cluster_token

    - name: Process namespace name to generate org_name
      set_fact:
        org_name: "ar-{{ env_name }}{{ namespace_name[6:] }}" 
        





    - name: Configure Quay
      quay_robot:
        name: "{{ org_name }}+deployer_quay"
        state: present
        quay_host: https://quay.apps.paashub.aramco.com.sa
        quay_token: "{{ quay_token }}"
        validate_certs: false
      register: robot_account_details

    - name: Set robot account token fact
      ansible.builtin.set_fact:
        robot_account_token: "{{ robot_account_details['token'] }}"

## Robot account token is saved in robot_account_token

    - name: Create OpenShift Docker registry secret for Quay
      command: |
        oc -n {{ namespace_name }} create secret docker-registry deployer-quay --docker-server={{ quay_host }} 
        --docker-username={{ org_name }}+deployer_quay --docker-password={{ robot_account_token }} 
      register: output
      failed_when:
        - output.rc != 0
        - "'already exists' not in output.stderr"

    # - name: Create Docker Registry secret for quay
    #   kubernetes.core.k8s:
    #     state: present
    #     validate_certs: false
    #     definition:
    #       kind: Secret
    #       apiVersion: v1
    #       metadata:
    #         name: deployer-quay
    #         namespace: "{{ namespace_name }}"
    #       data:
    #         .dockerconfigjson: "{{ { 'auths': { quay_host: { 'username': (org_name + '+deployer_quay'), 'password': robot_account_token } } }  }}"
    #       type: kubernetes.io/dockerconfigjson

