- name: Create Quay Organization
  hosts: localhost
  gather_facts: false
  collections:
    - infra.quay_configuration

  vars:
    namespace_name: ""
    env_name: ""
    quay_host: "https://quay.apps.paashub.aramco.com.sa"
    quay_token: "{{ quay_token }}" 
  tasks:

    - name: Validate namespace name starts with 'aramco-'
      fail:
        msg: "Invalid namespace_name '{{ namespace_name }}'. It must start with 'aramco-'."
      when: not namespace_name.startswith('aramco-')



    - name: Process namespace name to generate org_name
      set_fact:
        org_name: "ar-{{ env_name }}{{ namespace_name[6:] }}"

    - name: Configure Quay Organization
      infra.quay_configuration.quay_organization:
        name: "{{ org_name }}"
        state: present
        quay_host: "{{ quay_host }}"
        quay_token: "{{ quay_token }}"
        validate_certs: false
      register: output
